[versions]
kotlin = "2.1.20"
compose = "1.7.3"
dokka = "2.0.0"
githubManager = "1.0.1"
apiManager = "2.2.4"
richeditor = "1.0.0-rc11"
json = "20250107"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
githubManager = { module = "com.github.N7ghtm4r3:GitHubManager", version.ref = "githubManager" }
apiManager = { module = "com.github.N7ghtm4r3:APIManager", version.ref = "apiManager" }
richeditor = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditor" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
